name: CI workflow

on:
  pull request:
  push:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Install pre-commit
          run: uv pip install pre-commit
        - name Run pre-commit
          run: pre-commit run --all-files --show-diff-on-failure

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install nox
      
      - name: List installed packages
        run: pip list

      - name: Run tests with pytest & nox
        run: |
          nox -s tests-${{ matrix.python-version }}

